### PR TITLE
Feature: Login and Signup Pages

### PR DESCRIPTION
**Pull request by ntonioibarrola**
Transferring original login and signup functionality to the new login/signup design.

### CODE REVIEW

**Review by colinaguan — COMMENTED** [review]
do we have rights to the banners for login/signup? like is it under a creative commons license or anything?

**Comment by colinaguan** [comment]
you can also replace the old login and signup pages with your new ones; no need to have "TestLogin" or "TestSignUp" anymore

(I'll look at your code more in depth later)

**Comment by ntonioibarrola** [comment]
> do we have rights to the banners for login/signup? like is it under a creative commons license or anything?

I got the images from Figma. This is what they say about using stuff from Icons8 (which is where I got those images from).

**Pro License**
We offer both free and paid features within this plugin. Free access is limited to PNG in smaller sizes, whereas pro subscriptions grant a commercial license to all graphics in any format.

We offer an extensive free tier. All we ask is for you to add a link back to[ icons8.com](https://icons8.com/?utm_source=figma-plugin-icons8&utm_medium=cross-promo&utm_campaign=web-version), crediting us in the final work.

I can prob do a little caption somewhere that links them to that site or I can just find images elsewhere

**Review by zkm1 — APPROVED** [review]
Did a short functionality test, seems all good!

**Pull request merged**
